name: Monthly SNS Report

on:
  push:
  schedule:
    - cron: '*/5 * * * *'   # 5분마다 실행
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 라이브러리 설치
        run: pip install -r requirements.txt

      - name: 코드 실행
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          X_USERNAME: ${{ secrets.X_USERNAME }}
        run: python "유튜브_트위터_카운팅_노션기록까지.py"
